# Generated by Django 4.1.7 on 2023-03-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='bolim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlari', to='magazin.bolim'),
        ),
    ]
