# Generated by Django 4.1.7 on 2023-03-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0002_alter_mahsulot_bolim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='bolim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin.bolim'),
        ),
    ]
