# Generated by Django 4.1.7 on 2023-03-06 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0003_alter_mahsulot_bolim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='magazin.mahsulot'),
        ),
    ]
