# Generated by Django 4.1.7 on 2023-03-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0004_alter_media_mahsulot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin.mahsulot'),
        ),
    ]
