# Generated by Django 4.1.7 on 2023-03-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0006_izoh'),
    ]

    operations = [
        migrations.AddField(
            model_name='izoh',
            name='mahsulot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='magazin.mahsulot'),
        ),
    ]
