# Generated by Django 4.1.7 on 2023-03-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0007_izoh_mahsulot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izoh',
            name='matn',
            field=models.CharField(max_length=1000),
        ),
    ]
