# Generated by Django 4.1.7 on 2023-03-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0008_alter_izoh_matn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izoh',
            name='baho',
            field=models.FloatField(max_length=5),
        ),
    ]
