# Generated by Django 4.1.7 on 2023-03-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0009_alter_izoh_baho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izoh',
            name='sana',
            field=models.DateField(auto_now=True),
        ),
    ]
