# Generated by Django 4.1.7 on 2023-03-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0010_alter_izoh_sana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='chegirma',
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='miqdor',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
