# Generated by Django 4.1.7 on 2023-03-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0011_remove_mahsulot_chegirma_mahsulot_miqdor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='miqdor',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
