# Generated by Django 4.1.7 on 2023-03-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0012_alter_mahsulot_miqdor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='miqdor',
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='chegirma',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
