# Generated by Django 4.1.7 on 2023-03-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0013_remove_mahsulot_miqdor_mahsulot_chegirma'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='miqdor',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
