# Generated by Django 4.1.7 on 2023-03-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0002_buyurtma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyurtma',
            name='mahsulot',
        ),
    ]
