# Generated by Django 4.1.7 on 2023-03-10 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0010_alter_izoh_sana'),
        ('buyurtma', '0003_remove_buyurtma_mahsulot'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='mahsulot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='magazin.mahsulot'),
        ),
    ]
