# Generated by Django 4.1.7 on 2023-03-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0006_savat_miqdor_savat_umumiy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savat',
            name='miqdor',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
