# Generated by Django 4.1.7 on 2023-03-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='familia',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
